### ISSUE TITLE
reqwest 0.10

### ISSUE THREAD

**Issue by divergentdave** [divergentdave/certificate_carver#91]
Once Rust 1.39 is stable and reqwest 0.10 is out, we can use await with reqwest, and also drop cookie support with new optional features.

**Comment by divergentdave** [comment]
reqwest 0.10.0 is out, my WIP at 39e68036e34dd246594294d4563dae27e7a39b47 is crashing with this backtrace

```
thread 'main' panicked at 'not currently running on the Tokio runtime.', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.6/src/runtime/blocking/pool.rs:87:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::begin_panic
  12: std::thread::local::LocalKey<T>::with
  13: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
  14: <std::future::GenFuture<T> as core::future::future::Future>::poll
  15: <std::future::GenFuture<T> as core::future::future::Future>::poll
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
  17: <std::future::GenFuture<T> as core::future::future::Future>::poll
  18: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  19: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  20: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
  21: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  22: futures_util::future::future::chain::Chain<Fut1,Fut2,Data>::poll
  23: futures_util::future::try_future::try_chain::TryChain<Fut1,Fut2,Data>::poll
  24: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  25: <hyper::client::ResponseFuture as core::future::future::Future>::poll
  26: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
  27: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
  28: <std::future::GenFuture<T> as core::future::future::Future>::poll
  29: std::thread::local::LocalKey<T>::with
  30: std::thread::local::LocalKey<T>::with
  31: async_std::task::block_on::block_on
  32: <certificate_carver::crtsh::RealCrtShServer as certificate_carver::crtsh::CrtShServer>::check_crtsh
  33: <certificate_carver::crtsh::CachedCrtShServer<T> as certificate_carver::crtsh::CrtShServer>::check_crtsh
  34: certificate_carver::run
  35: certificate_carver::main
  36: std::rt::lang_start::{{closure}}
  37: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  38: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: std::panicking::try
             at src/libstd/panicking.rs:265
  41: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  42: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  43: main
  44: __libc_start_main
  45: _start
```

Maybe it's time to switch to surf instead
